param(
    [string]$TranslationDir = "translations",
    [string]$Output = "build/generated/lang.inc"
)

$ErrorActionPreference = "Stop"

function Read-TranslationFile {
    param([string]$Path)

    $json = Get-Content -LiteralPath $Path -Raw -Encoding UTF8 | ConvertFrom-Json
    if (-not $json.code) {
        throw "$Path is missing code"
    }
    if (-not $json.label) {
        throw "$Path is missing label"
    }
    if (-not $json.strings) {
        throw "$Path is missing strings"
    }
    return $json
}

function ConvertTo-SymbolSuffix {
    param([string]$Code)

    return ($Code.ToUpperInvariant() -replace '[^A-Z0-9]', '_')
}

function ConvertTo-CByteString {
    param([string]$Text)

    $bytes = [System.Text.Encoding]::UTF8.GetBytes($Text)
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append('"')
    foreach ($byte in $bytes) {
        if ($byte -eq 0) {
            throw "Translation strings cannot contain NUL bytes"
        }
        [void]$sb.Append(("\x{0:X2}" -f $byte))
    }
    [void]$sb.Append('"')
    return $sb.ToString()
}

$files = Get-ChildItem -LiteralPath $TranslationDir -Filter "*.json" | Sort-Object Name
if ($files.Count -eq 0) {
    throw "No translation JSON files found in $TranslationDir"
}

$languages = @()
foreach ($file in $files) {
    $languages += Read-TranslationFile -Path $file.FullName
}

$base = $languages | Where-Object { $_.code -eq "en" } | Select-Object -First 1
if (-not $base) {
    throw "translations/en.json is required as the fallback language"
}

$ids = @($base.strings.PSObject.Properties | ForEach-Object { $_.Name })
if ($ids.Count -eq 0) {
    throw "translations/en.json does not define any strings"
}

foreach ($language in $languages) {
    $props = @($language.strings.PSObject.Properties | ForEach-Object { $_.Name })
    $missing = @($ids | Where-Object { $_ -notin $props })
    $extra = @($props | Where-Object { $_ -notin $ids })
    if ($missing.Count -gt 0) {
        throw "$($language.code) is missing strings: $($missing -join ', ')"
    }
    if ($extra.Count -gt 0) {
        throw "$($language.code) has unknown strings: $($extra -join ', ')"
    }
}

$out = New-Object System.Collections.Generic.List[string]
$out.Add("/* Generated by tools/generate-translations.ps1. Do not edit directly. */")
$out.Add("")
$out.Add("typedef enum {")
foreach ($id in $ids) {
    $out.Add("    $id,")
}
$out.Add("    TR_LANGUAGE_COUNT")
$out.Add("} StringId;")
$out.Add("")

foreach ($language in $languages) {
    $suffix = ConvertTo-SymbolSuffix -Code $language.code
    $out.Add("static const char *const STRINGS_$suffix[TR_LANGUAGE_COUNT] = {")
    foreach ($id in $ids) {
        $text = [string]$language.strings.$id
        $out.Add("    [$id] = $(ConvertTo-CByteString -Text $text),")
    }
    $out.Add("};")
    $out.Add("")
}

$out.Add("static const char *const LANGUAGE_LABELS[LANG_COUNT] = {")
foreach ($language in $languages) {
    $suffix = ConvertTo-SymbolSuffix -Code $language.code
    $out.Add("    [LANG_$suffix] = $(ConvertTo-CByteString -Text ([string]$language.label)),")
}
$out.Add("};")
$out.Add("")

$out.Add("static const char *const *const LANGUAGE_TABLES[LANG_COUNT] = {")
foreach ($language in $languages) {
    $suffix = ConvertTo-SymbolSuffix -Code $language.code
    $out.Add("    [LANG_$suffix] = STRINGS_$suffix,")
}
$out.Add("};")
$out.Add("")

$out.Add("static int language_normalized(int language)")
$out.Add("{")
$out.Add("    return language >= LANG_EN && language < LANG_COUNT ? language : LANG_EN;")
$out.Add("}")
$out.Add("")
$out.Add("static const char *language_label(int language)")
$out.Add("{")
$out.Add("    const char *label = LANGUAGE_LABELS[language_normalized(language)];")
$out.Add("    return label ? label : LANGUAGE_LABELS[LANG_EN];")
$out.Add("}")
$out.Add("")
$out.Add("static const char *tr(StringId id)")
$out.Add("{")
$out.Add("    if ((unsigned)id >= (unsigned)TR_LANGUAGE_COUNT) {")
$out.Add('        return "";')
$out.Add("    }")
$out.Add("")
$out.Add("    int language = language_normalized(g_cfg.language);")
$out.Add("    const char *const *table = LANGUAGE_TABLES[language];")
$out.Add("    const char *text = table ? table[id] : NULL;")
$out.Add("    if (!text) {")
$out.Add("        text = STRINGS_EN[id];")
$out.Add("    }")
$out.Add('    return text ? text : "";')
$out.Add("}")

$outputDir = Split-Path -Parent $Output
if ($outputDir) {
    New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Resolve-Path -LiteralPath $outputDir).Path + [System.IO.Path]::DirectorySeparatorChar + (Split-Path -Leaf $Output), ($out -join [Environment]::NewLine) + [Environment]::NewLine, $utf8NoBom)
Write-Host "Generated $Output from $($files.Count) languages and $($ids.Count) strings."
